myblog/app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.IndexMain.as_view()),
    path("blog/", include("blog.urls")),
    path("user/", include("user.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    # 글 목록 조회
    path("", views.Index.as_view(), name="list"),
    # 글 상세 조회
    path("detail/<int:pk>/", views.Detail.as_view(), name="detail"),
    # 글 작성
    path("write/", views.Write.as_view(), name="write"),
    # 글 삭제
    path("detail/<int:pk>/delete/", views.Delete.as_view(), name="delete"),
    # 글 수정
    path("detail/<int:pk>/edit/", views.Update.as_view(), name="edit"),
    # 글 검색
    path('search/', views.SearchList.as_view(), name='search'),
    # 카테고리별 글 목록
    path("category/<str:category_name>/", views.CategoryPosts.as_view(), name="category_posts"),
    # 코멘트 작성
    path(
        "detail/<int:pk>/comment/write/", views.CommentWrite.as_view(), name="cm-write"
    ),
    # 코멘트 삭제
    path(
        "detail/comment/<int:pk>/delete/", views.CommentDelete.as_view(), name="cm-delete",
    ),
    # 이미지 업로드
    path('imageupload/', views.ImgUpload.as_view() , name='img-upload'),
]

myblog/user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    # user/ 로 시작
    # 회원가입
    path("register/", views.Registration.as_view(), name="register"),
    # 로그인
    path("login/", views.Login.as_view(), name="login"),
    # 로그아웃
    path("logout/", views.Logout.as_view(), name="logout"),
    # 프로필 수정
    path('edit/<str:username>/', views.ProfileEdit.as_view(), name='user_edit'),
]

myblog/user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    nickname = models.CharField(max_length=50, blank=True, null=True)
    profile_img = models.ImageField(upload_to = "profiles/", null=True, blank=True)

myblog/user/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.hashers import make_password
from django.contrib.auth.forms import PasswordChangeForm
from django import forms
from .models import User
from django.contrib.auth.forms import UserChangeForm

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'nickname', 'password1', 'password2', 'profile_img']

class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class ProfileEditForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['nickname', 'profile_img']

myblog/user/views.py
from django.shortcuts import render
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from .forms import RegisterForm, LoginForm, ProfileEditForm
from django.contrib.auth import authenticate, login, logout
from .models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

### 회원가입
class Registration(View):
    # 회원가입 정보 입력받음
    def get(self, request):
        # if request.user.is_authenticated:
        #     return redirect('blog:list')
        
        # 회원가입 페이지
        # => 정보를 입력할 폼을 보여줘야함
        form = RegisterForm()
        context = {"form": form}
        return render(request, "user/user_register.html", context)

    # 제출 눌렀을 때 동작
    def post(self, request):
        # 요청 넣은 채로 폼 만듦
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            # user모델 사용, form의 내용 저장
            user = form.save()
            # 로그인한 다음 이동
            return redirect("user:login")


### 로그인
class Login(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect("blog:list")

        form = LoginForm()
        context = {"form": form}
        return render(request, "user/user_login.html", context)

    def post(self, request):
        if request.user.is_authenticated:
            return redirect("blog:list")

        form = LoginForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            # boolean값으로 True/False로 반환
            user = authenticate(username=username, password=password)

            if user:
                login(request, user)
                return redirect("blog:list")

        form.add_error(None, "아이디가 없습니다.")

        # 에러가 들어있는 폼
        context = {"form": form}
        return render(request, "user/user_login.html", context)


### 로그아웃
class Logout(View):
    # 이미 로그인이 된 상태이므로 원래 유저가 정해져 있음
    def get(self, request):
        logout(request)
        return redirect("blog:list")
    

### 프로필 수정
class ProfileEdit(View):
    def get(self, request, username):
        user = get_object_or_404(User, username=username)
        form = ProfileEditForm(instance=user)
        password_change_form = PasswordChangeForm(user=request.user)
        context = {
            'user': user,
            'form': form,
            'password_change_form': password_change_form
        }
        return render(request, 'user/user_profile_edit.html', context)

    def post(self, request, username):
        user = get_object_or_404(User, username=username)
        form = ProfileEditForm(request.POST, request.FILES, instance=user)
        password_change_form = PasswordChangeForm(user=user, data=request.POST)

        # if form.is_valid() and password_change_form.is_valid():
        #     print(form.cleaned_data)
        #     form.save()
        #     print('view확인 ', user.nickname)
        #     print('view-save후 확인 ', user.nickname)
        #     password_change_form.save()  
        #     user.refresh_from_db()
        #     login(request, user)
        #     print('Nickname after saving:', user.nickname)
        #     return redirect('blog:list')
        if form.is_valid():
            form.save()

        if password_change_form.is_valid():
            password_change_form.save()  
            update_session_auth_hash(request, user) # 패스워드 변경 후 세션 갱신

        if form.is_valid() and password_change_form.is_valid():
            login(request, user)
            return redirect('blog:list')
        
        context = {
            'user': user,
            'form': form,
            'password_change_form': password_change_form
        }
        return render(request, 'user/user_profile_edit.html', context)

myblog/user/templates/user/user_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>My Blog</title>
		<!-- reset.css : meyerweb -->
		<link rel="stylesheet" href="{% static 'css/reset.css' %}" />
		<!-- font : pretendard -->
		<link rel="stylesheet" as="style" crossorigin href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css" />

		<link rel="stylesheet" href="{% static 'css/global.css' %}" />

		<!-- layout -->
		<link rel="stylesheet" href="{% static 'css/header.css' %}" />
		<link rel="stylesheet" href="{% static 'css/footer.css' %}" />
		<link rel="stylesheet" href="{% static 'css/about.css' %}" />

		<!-- component -->
		<link rel="stylesheet" href="{% static 'css/button.css' %}" />
		<link rel="stylesheet" href="{% static 'css/banner.css' %}" />
		<link rel="stylesheet" href="{% static 'css/category.css' %}" />
		<link rel="stylesheet" href="{% static 'css/author.css' %}" />

		<link rel="stylesheet" href="{% static 'css/post.css' %}" />
		<link rel="stylesheet" href="{% static 'css/posts.css' %}" />
		<link rel="stylesheet" href="{% static 'css/main.css' %}" />

		<style>
			.search {
				border: 5px solid black;
				border-radius: 10px;
				padding: 5px;
			}

			.search-icon {
				width:40px;
				height:40px;
			}

			.search-btn {
				border: none;
				margin-left: 5px;
				background-color: white;
			}

			.search-box {
				display: flex;
			}

			.select-all {
				background-color: #f5d3cc !important;
				padding: 5px 15px !important;
			}

			.views-box {
				display: flex;
				justify-content: flex-end;
				font-size: small;
			}

			.views {
				color: #ff612f;
				font-weight: bold;
				white-space: pre;
			}

			.heart {
				width:18px;
				height:18px;
			}

			.username {
				color: #000000;
				padding: 0px 0 30px;
				font-size: small;
			}

			.profile-edit-btn {
				display: flex;
				justify-content: flex-end;
			}

      .profile-box {
        border-top: 1px solid black;
        padding: 50px;
        display: flex;
        justify-content: center;
      }

      .profile-title {
        font-weight: bold;
        font-size: xx-large;
      }
      
      .profile-content {
        border: 10px solid #37aaec;
        padding: 20px;
        border-radius: 20px;
        margin-top: 50px;
      }

      .profile-image {
        width: 300px;
        height: 300px;
      }

      #preview {
				width: 300px;
				height: 300px;
				padding: 20px;
			}
			
			.image-box {
				display:flex;
				flex-direction: column;
			}
		</style>
</head>
<body>
  {% block content %}
  <!-- header -->
  <header>
    <div class="max-width">
      <h1>
        <a href="{% url 'blog:list' %}">
          <img src="{% static 'assets/Logo.svg' %}" alt="My Blog" />
        </a>
      </h1>

      <form action="{% url 'blog:search' %}" method="get">
      <div class="search-box">
            <input class="search" type="text" name="search">
            <button type="submit" class="search-btn">
                <img class="search-icon" src="{% static 'assets/search.png' %}" alt="search">
            </button>
        </form>
      </div>

      <ul>
        <!--프사-->
        <li class="profile-img">
          <a href="#">
            {% if user.profile_img %}
            <img src="{{ user.profile_img.url }}" alt=""/>
            {% endif %}
          </a>
        </li>
        <!--글 작성 버튼-->
        {% if user.is_authenticated %}
        <li>
          <a href="{% url 'blog:write' %}" class="button">
            <img src="{% static 'assets/icon-modify-white.svg' %}" alt="" />
            <span>Write</span>
          </a>
        </li>
        {% else %}
        <li class="only-pc">
          <a href="{% url 'user:register' %}" class="button gray">
            <img src="{% static 'assets/icon-register.svg' %}" alt="" />
            <span>Register</span>
          </a>
        </li>
        {% endif %}
      
        {% if user.is_authenticated %}
        <!--로그아웃 버튼-->
        <li>
          <a href="{% url 'user:logout' %}" class="button white">
            <img src="{% static 'assets/icon-logout.svg' %}" alt="" />
            <span>Logout</span>
          </a>
        </li>
        {% else %}
        <!--로그인 버튼-->
        <li>
          <a href="{% url 'user:login' %}" class="button gray">
            <img src="{% static 'assets/icon-login.svg' %}" alt="" />
            <span>Login</span>
          </a>
        </li>
        {% endif %}

        <!--
        <li class="only-pc">
          <a href="#" class="button gray">
            <img src="./assets/icon-register.svg" alt="" />
            <span>Register</span>
          </a>
        </li>
        -->
        
      </ul>
    </div>
  </header>
  <!--// header -->

  <div class="profile-box">
    <div class="profile-content">
      <h2 class="profile-title">Login</h2>
      <hr>
      
      <form action="{% url 'user:login' %}" method="POST">
        {% csrf_token %}
        
        {{ form.as_p }}
        
        <button type="submit">Login</button>
      </form>
    </div>
    {% endblock %}
  </div>

</body>
</html>

myblog/user/templates/user/user_profile_edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>My Blog</title>
		<!-- reset.css : meyerweb -->
		<link rel="stylesheet" href="{% static 'css/reset.css' %}" />
		<!-- font : pretendard -->
		<link rel="stylesheet" as="style" crossorigin href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css" />

		<link rel="stylesheet" href="{% static 'css/global.css' %}" />

		<!-- layout -->
		<link rel="stylesheet" href="{% static 'css/header.css' %}" />
		<link rel="stylesheet" href="{% static 'css/footer.css' %}" />
		<link rel="stylesheet" href="{% static 'css/about.css' %}" />

		<!-- component -->
		<link rel="stylesheet" href="{% static 'css/button.css' %}" />
		<link rel="stylesheet" href="{% static 'css/banner.css' %}" />
		<link rel="stylesheet" href="{% static 'css/category.css' %}" />
		<link rel="stylesheet" href="{% static 'css/author.css' %}" />

		<link rel="stylesheet" href="{% static 'css/post.css' %}" />
		<link rel="stylesheet" href="{% static 'css/posts.css' %}" />
		<link rel="stylesheet" href="{% static 'css/main.css' %}" />

		<style>
			.search {
				border: 5px solid black;
				border-radius: 10px;
				padding: 5px;
			}

			.search-icon {
				width:40px;
				height:40px;
			}

			.search-btn {
				border: none;
				margin-left: 5px;
				background-color: white;
			}

			.search-box {
				display: flex;
			}

			.select-all {
				background-color: #f5d3cc !important;
				padding: 5px 15px !important;
			}

			.views-box {
				display: flex;
				justify-content: flex-end;
				font-size: small;
			}

			.views {
				color: #ff612f;
				font-weight: bold;
				white-space: pre;
			}

			.heart {
				width:18px;
				height:18px;
			}

			.username {
				color: #000000;
				padding: 0px 0 30px;
				font-size: small;
			}

			.profile-edit-btn {
				display: flex;
				justify-content: flex-end;
			}

      .profile-box {
        border-top: 1px solid black;
        padding: 50px;
        display: flex;
        justify-content: center;
      }

      .profile-title {
        font-weight: bold;
        font-size: xx-large;
      }
      
      .profile-content {
        border: 10px solid #37aaec;
        padding: 20px;
        border-radius: 20px;
        margin-top: 50px;
      }

      .profile-image {
        width: 300px;
        height: 300px;
      }

      #preview {
				width: 300px;
				height: 300px;
				padding: 20px;
			}
			
			.image-box {
				display:flex;
				flex-direction: column;
			}
		</style>
</head>
<body>
  {% block content %}
		<!-- header -->
		<header>
			<div class="max-width">
				<h1>
					<a href="{% url 'blog:list' %}">
						<img src="{% static 'assets/Logo.svg' %}" alt="My Blog" />
					</a>
				</h1>

				<form action="{% url 'blog:search' %}" method="get">
				<div class="search-box">
							<input class="search" type="text" name="search">
							<button type="submit" class="search-btn">
									<img class="search-icon" src="{% static 'assets/search.png' %}" alt="search">
							</button>
					</form>
				</div>

				<ul>
					<!--프사-->
					<li class="profile-img">
						<a href="#">
							{% if user.profile_img %}
							<img src="{{ user.profile_img.url }}" alt=""/>
							{% endif %}
						</a>
					</li>
					<!--글 작성 버튼-->
					{% if user.is_authenticated %}
					<li>
						<a href="{% url 'blog:write' %}" class="button">
							<img src="{% static 'assets/icon-modify-white.svg' %}" alt="" />
							<span>Write</span>
						</a>
					</li>
					{% else %}
					<li class="only-pc">
						<a href="{% url 'user:register' %}" class="button gray">
							<img src="{% static 'assets/icon-register.svg' %}" alt="" />
							<span>Register</span>
						</a>
					</li>
					{% endif %}
				
					{% if user.is_authenticated %}
					<!--로그아웃 버튼-->
					<li>
						<a href="{% url 'user:logout' %}" class="button white">
							<img src="{% static 'assets/icon-logout.svg' %}" alt="" />
							<span>Logout</span>
						</a>
					</li>
					{% else %}
					<!--로그인 버튼-->
					<li>
						<a href="{% url 'user:login' %}" class="button gray">
							<img src="{% static 'assets/icon-login.svg' %}" alt="" />
							<span>Login</span>
						</a>
					</li>
					{% endif %}

					<!--
					<li class="only-pc">
						<a href="#" class="button gray">
							<img src="./assets/icon-register.svg" alt="" />
							<span>Register</span>
						</a>
					</li>
          -->
					
				</ul>
			</div>
		</header>
		<!--// header -->


  <div class="profile-box">
    <div class="profile-content">
      <h2 class="profile-title">Profile Edit</h2>
      <hr>
      
      <form action="{% url 'user:user_edit' user.username %}"  method="POST" enctype="multipart/form-data">
        {% csrf_token %}
      
        <p>id: {{ user.username }}</p>
        {% comment %} <p>profile-image: <img class="profile-image" src="{{ user.profile_img.url }}" alt=""></p> {% endcomment %}
        <div class="image-box">
          <input type="file" id="id_profile_img" name="profile_img" onchange="readURL(this);">
          <img id="preview" src="{% if user.profile_img %}{{ user.profile_img.url }}{% else %}{% static 'images/default.png' %}{% endif %}" alt="Image Preview">
        </div>
        <p>nickname: {{ form.nickname }}</p>

        <h3>Change Password</h3>
        {{ password_change_form.as_p }}
        <button type="submit">Save</button>
      </form>
    </div>
    {% endblock %}
  </div>

  <script>
    function readURL(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function(e) {
          document.getElementById('preview').src = e.target.result;
        };
        reader.readAsDataURL(input.files[0]);
      } else {
        document.getElementById('preview').src = "";
      }
    }
  </script>
</body>
</html>

myblog/user/templates/user/user_register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>My Blog</title>
		<!-- reset.css : meyerweb -->
		<link rel="stylesheet" href="{% static 'css/reset.css' %}" />
		<!-- font : pretendard -->
		<link rel="stylesheet" as="style" crossorigin href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css" />

		<link rel="stylesheet" href="{% static 'css/global.css' %}" />

		<!-- layout -->
		<link rel="stylesheet" href="{% static 'css/header.css' %}" />
		<link rel="stylesheet" href="{% static 'css/footer.css' %}" />
		<link rel="stylesheet" href="{% static 'css/about.css' %}" />

		<!-- component -->
		<link rel="stylesheet" href="{% static 'css/button.css' %}" />
		<link rel="stylesheet" href="{% static 'css/banner.css' %}" />
		<link rel="stylesheet" href="{% static 'css/category.css' %}" />
		<link rel="stylesheet" href="{% static 'css/author.css' %}" />

		<link rel="stylesheet" href="{% static 'css/post.css' %}" />
		<link rel="stylesheet" href="{% static 'css/posts.css' %}" />
		<link rel="stylesheet" href="{% static 'css/main.css' %}" />

		<style>
			.search {
				border: 5px solid black;
				border-radius: 10px;
				padding: 5px;
			}

			.search-icon {
				width:40px;
				height:40px;
			}

			.search-btn {
				border: none;
				margin-left: 5px;
				background-color: white;
			}

			.search-box {
				display: flex;
			}

			.select-all {
				background-color: #f5d3cc !important;
				padding: 5px 15px !important;
			}

			.views-box {
				display: flex;
				justify-content: flex-end;
				font-size: small;
			}

			.views {
				color: #ff612f;
				font-weight: bold;
				white-space: pre;
			}

			.heart {
				width:18px;
				height:18px;
			}

			.username {
				color: #000000;
				padding: 0px 0 30px;
				font-size: small;
			}

			.profile-edit-btn {
				display: flex;
				justify-content: flex-end;
			}

      .profile-box {
        border-top: 1px solid black;
        padding: 50px;
        display: flex;
        justify-content: center;
      }

      .profile-title {
        font-weight: bold;
        font-size: xx-large;
      }
      
      .profile-content {
        border: 10px solid #37aaec;
        padding: 20px;
        border-radius: 20px;
        margin-top: 50px;
      }

      .profile-image {
        width: 300px;
        height: 300px;
      }

      #preview {
				width: 300px;
				height: 300px;
				padding: 20px;
			}
			
			.image-box {
				display:flex;
				flex-direction: column;
			}
		</style>
</head>
<body>
  {% block content %}
		<!-- header -->
		<header>
			<div class="max-width">
				<h1>
					<a href="{% url 'blog:list' %}">
						<img src="{% static 'assets/Logo.svg' %}" alt="My Blog" />
					</a>
				</h1>

				<form action="{% url 'blog:search' %}" method="get">
				<div class="search-box">
							<input class="search" type="text" name="search">
							<button type="submit" class="search-btn">
									<img class="search-icon" src="{% static 'assets/search.png' %}" alt="search">
							</button>
					</form>
				</div>

				<ul>
					<!--프사-->
					<li class="profile-img">
						<a href="#">
							{% if user.profile_img %}
							<img src="{{ user.profile_img.url }}" alt=""/>
							{% endif %}
						</a>
					</li>
					<!--글 작성 버튼-->
					{% if user.is_authenticated %}
					<li>
						<a href="{% url 'blog:write' %}" class="button">
							<img src="{% static 'assets/icon-modify-white.svg' %}" alt="" />
							<span>Write</span>
						</a>
					</li>
					{% else %}
					<li class="only-pc">
						<a href="{% url 'user:register' %}" class="button gray">
							<img src="{% static 'assets/icon-register.svg' %}" alt="" />
							<span>Register</span>
						</a>
					</li>
					{% endif %}
				
					{% if user.is_authenticated %}
					<!--로그아웃 버튼-->
					<li>
						<a href="{% url 'user:logout' %}" class="button white">
							<img src="{% static 'assets/icon-logout.svg' %}" alt="" />
							<span>Logout</span>
						</a>
					</li>
					{% else %}
					<!--로그인 버튼-->
					<li>
						<a href="{% url 'user:login' %}" class="button gray">
							<img src="{% static 'assets/icon-login.svg' %}" alt="" />
							<span>Login</span>
						</a>
					</li>
					{% endif %}

					<!--
					<li class="only-pc">
						<a href="#" class="button gray">
							<img src="./assets/icon-register.svg" alt="" />
							<span>Register</span>
						</a>
					</li>
          -->
					
				</ul>
			</div>
		</header>
		<!--// header -->


  <div class="profile-box">
    <div class="profile-content">
      <h2 class="profile-title">Register</h2>
      <hr>
      
      <form action="{% url 'user:register' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        {{ form.as_p }}
        
        <button type="submit">Register</button>
      </form>
    </div>
    {% endblock %}
  </div>

</body>
</html>